### ISSUE TITLE
Pull access denied

### ISSUE THREAD

**Issue by weirdvic** [wastrachan/docker-dhcpd#1]
When trying to run command 
`docker pull wastrachan/docker-dhcpd`
I get the message:
`Error response from daemon: pull access denied for wastrachan/docker-dhcpd, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`
Is this image restricted for public access now?

**Comment by wastrachan** [comment]
@weirdvic Nope, it just looks like there's a typo in my README! While `docker-dhcpd` is the name of this repository, the image is just `dhcpd`.

You'd want `docker pull wastrachan/dhcpd`

**Comment by jonapoul** [comment]
Just a heads-up and apologies for reviving a long-dead issue: this typo is still visible in the Docker Hub readme: https://hub.docker.com/r/wastrachan/dhcpd

Had me confused for an embarassing amount of time!
